return {}
-- vim.lsp.config('pyright', {
--   settings = {
--     pyright = {
--       -- Using Ruff's import organizer
--       disableOrganizeImports = true,
--     },
--     python = {
--       analysis = {
--         -- Ignore all files for analysis to exclusively use Ruff for linting
--         diagnosticMode = 'workspace',
--         ignore = { '*' },
--       },
--     },
--   },
-- })
-- vim.lsp.enable 'pyright'
-- vim.lsp.config('ruff', {
--   init_options = {
--     settings = {
--       -- Ruff language server settings go here
--       organizeImports = false,
--       logLevel = 'debug',
--     },
--   },
-- })
--
-- vim.lsp.enable 'ruff'
